development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] || ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  channel_prefix: customer_portal_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
