shopify:
  app_id: xxx
  key: xxx
  secret: xxx
  app_slug: xxx
https_url: https://xxx.ap.ngrok.io
asset_host: ''
secret_key_base: xxx
from_email: xxx
google_recaptcha_site_key: xxx
google_recaptcha_secret_key: xxx
sidekiq:
  username: xxx
  secret: xxx
admin_google_oauth:
  id: xxx
  secret: xxx
aws:
  access_key_id: xxx
  secret_access_key: xxx
  region: us-east-1
sendinblue:
  api_key: xxx
  main_list_id: xxx
rollbar:
  backend_access_token: xxx
